name: Pages sync (data -> docs)
on:
  push:
    branches: [ main ]
    paths:
      - "data/cases.json"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy data -> docs
        run: |
          mkdir -p docs
          cp -f data/cases.json docs/cases.json
      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/cases.json
          git commit -m "chore: sync cases.json -> docs" || echo "no changes"
          git push
