name: Pages sync (data + images)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'data/**'
      - 'images/**'
      - 'docs/app.js'
      - 'docs/index.html'
      - '.github/workflows/pages-sync.yml'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sync data + images into docs
        run: |
          mkdir -p docs/images
          cp -f data/cases.json docs/cases.json
          rsync -a --delete images/ docs/images/
          # 兜底占位图（万一忘了上传）
          if [ ! -f docs/images/placeholder.svg ]; then
            cat > docs/images/placeholder.svg <<'SVG'
<svg xmlns="http://www.w3.org/2000/svg" width="800" height="500"><rect width="100%" height="100%" fill="#f2f2f2"/><text x="50%" y="50%" font-size="24" text-anchor="middle" fill="#999">preview</text></svg>
SVG
          fi

      # 下面两步只在你把 Pages 设置为 “GitHub Actions” 源时需要；
      # 如果你用的是 “/docs” 作为 Pages 源，可以删掉这两步。
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs
      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
