name: Pages sync (data + images)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'data/**'
      - 'images/**'
      - 'docs/**'
      - '.github/workflows/pages-sync.yml'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare docs assets
        run: |
          set -e
          mkdir -p docs/images
          # 1) 同步结构化数据到 docs 根
          cp -f data/cases.json docs/cases.json
          # 2) 镜像 images/ 到 docs/images/ （保持同名层级）
          rsync -a --delete images/ docs/images/

      - name: Commit & push changes to docs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(pages): sync data & images to docs"
          branch: main
