name: Pages sync (data -> docs)

on:
  push:
    branches: [ "main" ]
    paths:
      - "data/cases.json"
      - "images/**"
      - "docs/**"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare docs assets
        run: |
          mkdir -p docs/images
          rsync -av --delete images/ docs/images/
          cp -f data/cases.json docs/cases.json

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain docs)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add docs/cases.json docs/images
            git commit -m "chore(pages): sync data -> docs"
            git push
          else
            echo "No changes to commit."
          fi
